# Generated by Django 4.2.29 on 2026-04-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_watchedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
